import Footer from "@/components/global/Footer";
import Navbar from "@/components/global/Navbar";
import "./globals.css";


export const metadata = {
  title: "Forcythe Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gradient`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
